config/routes.rb
Rails.application.routes.draw do

	  root 'pages#home'

  	get  '/about',   to: 'pages#about'
  	get  '/contact', to: 'pages#contact'
  	
    get    '/signup',  to: 'users#new'
    post   '/signup',  to: 'users#create'


    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'
      	
    resources :users

    delete  '/projects/:id/delete',  to: 'projects#destroy',  as: 'destroy_project'
    post  '/projects/:id/edit', to: 'projects#edit', as: 'edit_project'
    post   '/projects/:id', to: 'projects#update', as: 'update_project'

    get   '/visitors', to: 'visitors#index',  as: 'index'
    post  '/visitors', to: 'visitors#view',   as: 'view'

    get    '/projects/new',  to: 'projects#new', as: 'project_new'
    get   '/projects/registered',  to: 'projects#registered', as: 'show_projects'
    get    '/projects/:id/info',  to: 'projects#info', as: 'info_project'
    resources :projects
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/faq.rb
class Faq < ApplicationRecord
	belongs_to :project
end

app/models/project.rb
class Project < ApplicationRecord
	belongs_to :user
	has_many :faqs

	mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord

	attr_accessor :remember_token

  has_many :projects

	before_save { name.downcase! }
	before_save { email.downcase! }
	
	validates :name, presence: true

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: { case_sensitive: false }


	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }

	# Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
  	return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@projects = Project.all
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	def index
		@projects = Project.where(user_id: current_user.id)
	end
	
	def new
		@project = Project.new
	end

	def create
		@project = Project.new(project_params)
		if @project.title != ""
			@project.save
			redirect_to projects_path
		else
			redirect_to new_project_path
		end
	end

	def edit
		@project = Project.find(params[:id])
		@project.image.cache!
	end

	def update
		p params
		@project = Project.find(params[:id])
		if @project.update(project_params)
			redirect_to show_projects_path
		else
			render 'edit'
		end
	end

	def destroy
		@project = Project.find(params[:id])
		@project.destroy
		redirect_to show_projects_path
	end

	def registered
		@projects = Project.all
	end

	def info
		@project = Project.find(params[:id])
	end

	private
  
  	def project_params
			params.require(:project).permit([:user_id, :title, :short_description, :description, :image, :status])
		end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end
  

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	  def new
  		@user = User.new
  	end

  	def show
      @user = User.find(current_user.id)
  	end

    def edit
      p @user_edit = User.find(params[:id])
    end

  	def create
    	@user = User.new(user_params)
    	if @user.save
        last = User.last
        if current_user
          redirect_to index_url
        else
    		  log_in @user
      		flash[:success] = "Welcome!"
      		redirect_to @user
        end
    	else
      		render 'new'
    	end
  	end

    def update
      if User.find(params[:id].to_i).email == params[:user][:email]
        User.update(params[:id].to_i, 
                    name: params[:user][:name],
                    phone_number: params[:user][:phone_number])
      else
        User.update(params[:id].to_i, 
                    name: params[:user][:name],
                    phone_number: params[:user][:phone_number],
                    email: params[:user][:email])
      end
      render :controller => 'user', :action => 'registred' 
    end


	private

    	def user_params
      		params.require(:user).permit(:name, :email, :phone_number, :password,
                                   :password_confirmation, :admin)
    	end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def index
  	@user = User.find(current_user.id)
  	render 'users/show'
  end

  def view
  	redirect_to index_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	# Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Returns the user corresponding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      #raise       # The tests still pass, so this branch is currently untested.
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # def log_admin
  #   User.find_by(id: @current_user.id)
  # end
  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper

end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/layouts/_footer.html.erb
<div class="container">
	<footer class="footer">
	  <small>
	   Fondify by Herdez
	  </small>
	  <nav>
	    <ul>
	      <li><%= link_to "About",   '#' %></li>
	      <li><%= link_to "Contact", '#' %></li>
	    </ul>
	  </nav>
	</footer>
</div>

app/views/layouts/_header.html.erb
<header>
<nav class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">

    <nav> 
        <ul class="nav navbar-nav navbar-left">
            <li><%= link_to "Fondify", '#', id: "logo" %></li>
        </ul>
    </nav>

    <nav>
        <ul class="nav navbar-nav navbar-right">

            <% if logged_in? %>

                <% if current_user.admin %>
                  <li><%= link_to "Projects", show_projects_path %></li>
                <% else %>
                  <li><%= link_to "My Projects", projects_path %></li>
                <% end %>

                <li class="dropdown">

                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user"><%= current_user.name %><b class="caret"></b></a> 
                
                <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                    <li><%= link_to "Profile", current_user %></li>
                    <li><%= link_to "Settings", '#' %></li>
                    <li class="divider"></li>
                    <li><%= link_to "Log out", logout_path, method: :delete %></li>
                </ul>
                </li>
            <% else %>
                <li><%= link_to "Home", root_path %></li>
                <li><%= link_to "Log in", login_path %></li>
                <li><%= link_to "Sign up", signup_path %><li>
            <% end %>
        </ul>
    </nav>
    </div>
</header>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">

<!--  -->
<!-- <link href="styles/ihover.css" rel="stylesheet"> -->
<!--  -->

  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Template" %></title>

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= render 'layouts/shim' %>



    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Template" %>">
    
  </head>

  <body>

    <%= render 'layouts/header' %>

    <div class="container">
    <main role="main">
      <div class='container'>
        
        <% flash.each do |message_type, message| %>
          <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
        <% end %>

        <%= yield %>

        
        <div id='remote_container'></div>
      </div>
    </main>

    <%= render 'layouts/footer' %>

  </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="bg"></div>
	<div class="jumbotron">
	  <h1>Welcome to Fondify</h1>
	</div>
</div>

  <div class="row pro-projects">
	      <div class="col-lg-12">
	          <h1>Founding New Generation of Pro Social Projects</h1>
	      </div>
	      <% 3.times do %>
           <div class="col-lg-4 col-md-4">
	              <div class="panel">
	                      <div class="panel-heading">
	                          <div>
	                              <%= link_to image_tag("logo.png"), class: 'center-block' %>
	                          </div>
	                      </div>
	                  <div class="panel-body">
	                          <div class="new-flag">Project Social Founding</div>
	                      <hr/>
	                      <div class="title">
	                          <%= link_to "Social Founding to Regional Products" %>
	                      </div>
	                      <ul class="nav nav-pills vote">
	                        <li><span id="average_rating_21"></span></li>
	                        <li> &nbsp; <span>(47 reviews)</span></li>
	                      </ul>
	                      <p><i class="fa fa-clock-o fa-lg"></i> &nbsp; <span>10 hours</span></p>
	                      <div class="stack-group">
	                                  <span class="stack">Ruby on Rails |</span>
	                                  <span class="stack"> Bootstrap |</span>
	                                  <span class="stack"> jQuery</span>
	                      </div>
	                  </div>

	              </div>
	          </div>
         <% end %>
	      <% @projects.each do |project| %>
          <% if project.status == true %>
	          <div class="col-lg-4 col-md-4">
	              <div class="panel">
                    <div class="panel-heading">
                        <div>
                            <%= link_to image_tag(project.image_url(:thumb).to_s), info_project_path(project), remote: true %>
                        </div>
                    </div>
	                  <div class="panel-body">
	                      <div class="new-flag"><%= project.title %></div>
	                      <hr/>
	                      <div class="title">
	                          <%= link_to project.description, info_project_path(project), remote: true %>
	                      </div>
	                      <ul class="nav nav-pills vote">
	                        <li><span id="average_rating_21"></span></li>
	                        <li> &nbsp; <span>(47 reviews)</span></li>
	                      </ul>
	                      <p><i class="fa fa-clock-o fa-lg"></i> &nbsp; <span>10 hours</span></p>
	                      <div class="stack-group">
	                                  <span class="stack">Ruby on Rails |</span>
	                                  <span class="stack"> Bootstrap |</span>
	                                  <span class="stack"> jQuery</span>
	                      </div>
	                  </div>

	              </div>
	          </div>
	        <% end %>
        <% end %>
  </div>

app/views/projects/_info.html.erb
<div id="project-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><%= title %></h4>
      </div>
        <div class="modal-body">
          <div class="alert alert-danger" role="alert" style="display: none;"></div>
          <div class="form-group">
            <h3>Title</h3>
            <p><%= @project.title %></p> 
          </div>
          <div class="form-group">
            <h3>Description</h3>
            <p><%= @project.description %></p> 
          </div>
        </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/projects/edit.html.erb
<% if current_user.admin == true %>
  <% provide(:title, 'Edit Project') %>
  <h3>Edit Project of <%= User.find(@project.user_id).name %></h3>
  <%= form_for @project, url: update_project_path(@project), :method => :POST do |f| %>
    <p>
      <%= f.hidden_field :user_id, :value => @project.user_id, class: "input" %>
    </p>
    <%= f.label :title %>
  	<p>
      <%= f.text_field :title, class: "input" %>
    </p>
    <%= f.label :Description %>
    <p>
      <%= f.text_field :description, class: "input" %>
    </p>
    <p>
      <label>Upload a Picture</label>
      <%= f.file_field :image %>
      <%= f.hidden_field :image_cache %>
    </p>
    <div class="image-pre">
        <%= image_tag(@project.image_url(:thumb)) if @project.image? %>
    </div>
    <%= "Status of Accepted" %>
    <p>
      <%= f.text_field :status, class: "input" %>
    </p>
    <p>
      <%= f.submit "Save", class: "button is-primary is-large" %>
    </p>
  <% end %>
<% end %>


  

app/views/projects/index.html.erb
<div class="block">
    <%= link_to "Add New Project", new_project_path, class: "btn btn-large btn-warning" %>
</div>

<% if @projects %>
	<h1>Projects</h1>
	<div class="row">
	<table class="table table-striped">
	 <tr class="something">
	   <th id="tabletitle1" class="col-md-2">Title</th>
	   <th id="tabletitle2" class="col-md-2">Description</th>
	   <th id="tabletitle3" class="col-md-2">Image</th>
	   <th id="tabletitle3" class="col-md-4">Status</th>
	   <th colspan="6"></th>
	 </tr>
	 <% @projects.each do |project| %>
	   <tr>
	     <td><%= project.title %></td>
	     <td><%= project.description %></td>
	     <td><%= image_tag(project.image_url(:thumb)) if project.image? %></td>
	     <% if project.status == false %>
	       <td>No Accept</td></td>
	     <% else %>
	       <td>Accept</td></td>
	     <% end %>
	   </tr>
	 <% end %>
	</table>
	</div>
<% end %>

app/views/projects/info.js.erb
$('<%= j render "projects/info", title: "Info Project" %>').on('hidden.bs.modal', function (e) {
	  $(this).remove();
	  $('.modal-backdrop').remove();
}).modal();

app/views/projects/new.html.erb
<% provide(:title, 'New Project') %>
<h3>New Project</h3>
<%= form_for @project, url: projects_path, :method => :POST do |f| %>
  <p>
    <%= f.hidden_field :user_id, :value => current_user.id, class: "input" %>
  </p>
  <%= f.label :title %>
	<p>
    <%= f.text_field :title, class: "input" %>
  </p>
  <%= f.label :Description %>
  <p>
    <%= f.text_field :description, class: "input" %>
  </p>
  <div class='field'>
    <%= f.file_field :image %>
  </div>
  <p>
    <%= f.submit "Save", class: "button is-primary is-large" %>
  </p>
<% end %>

app/views/projects/registered.html.erb
<h1>Administrator</h1>

<div class="container">

    <h3>Info Projects</h3>

    <table class="table table-bordered table-striped" >
        <thead>
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Image</th>
            <th>Status</th>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
        </tr>
        </thead>

    <% if @projects %>
	    <div class="data" > 
		    <% @projects.each do |project| %> 
		        <tr>
		            <td><%= project.title %></td>
		            <td><%= project.description %></td>
		            <td><%= image_tag(project.image_url(:thumb)) if project.image? %></td>
		            <td><%= project.status %></td>

		            <td><%= button_to 'Edit', edit_project_path(project), class: 'btn btn-primary' %></td>
	              <td><%= button_to 'Destroy', destroy_project_path(project), class: 'btn btn-danger', method: :delete,
                                  data: { confirm: "You sure?" } %></td>
		        </tr>
			  <% end %>
	    </div>
    <% end %>

</table>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_new_admin.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/_new_user.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">


    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>


      <%= f.submit "Add User¡", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Administrator</h1>
	
<div class="container">
	
	<h3>Info Data</h3>

	<div class="row">
  <div class="col-md-6 col-md-offset-3">


    <%= form_for(@user_edit, url: to_update_user_path(@user_edit.id)) do |f| %>
      
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>


      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

   
      <div class="form-actions">
    <%= f.submit 'Make Changes¡', 
                class: 'btn btn-danger', 
                data: { confirm: 'Are you sure to make changes for the user?' } %>
  </div>


    <% end %>
  </div>
</div>


</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<% if current_user %>
  <h1>Adding a New User</h1>
  <%= render 'users/new_user' %>
<% else %>
  <h1>Sign up</h1>
  <%= render 'users/new_admin' %>
<% end %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>


<% if current_user.admin %>
	<h1>Welcome Administrator <%= @user.name %></h1>
<% else %>
	<h1>Welcome <%= @user.name %>!</h1>
	<div>
		 <div class="inner">
	     <%= link_to image_tag("goal.png", size: "150x150", alt: "Projects"), new_project_path %>
	   </div>
	   <div class="inner">
	     <h4>Add New Project</h4>
	   </div>
	</div>
<% end %>